baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "tranquil-peak-theme"

[permalinks]
  posts = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

  [author]
  name = "Chubi Chu"
  bio = "non tech"
  job = "student"
  location = "Denmark"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  # gravatarEmail = "thibaud.lepretre@gmail.com"
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "/img/specs2.jpg"

# Menu Configuration    
[[menu.main]]
  weight = 0
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\" title='Home'></i>"
  url = "/"
[[menu.main]]
  weight = 1
  identifier = "post"
  name = "Blog"
  pre = "<i class=\"sidebar-button-icon fab fa-blogger-b\" title='Blog'></i>"
  url = "/post"
[[menu.main]]
  weight = 2
  identifier = "projects"
  name = "Projects"
  pre = "<i class=\"sidebar-button-icon fas fa-chart-area\" title='Projects'></i>"
  url = "/post/projects"

  [[menu.links]]
  weight = 3
  identifier = "linkedin"
  name = "Linkedin"
  pre = "<i class=\"sidebar-button-icon fab fa-linkedin\" title='LinkedIn'></i>"
  url = "https://www.linkedin.com/in/antarlina-mukherjee-453052a2/"

[params]
  sidebarBehavior = 2
  coverImage = "/img/luxuryblue2.jpg"